/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author unifgalvarenga
 */
public class telaPlayslistUser extends javax.swing.JFrame {

    /**
     * Creates new form telaPlayslistUser
     */
    public telaPlayslistUser() {
        initComponents();
    }

    public JButton getBt_adicionarMusica() {
        return bt_adicionarMusica;
    }

    public void setBt_adicionarMusica(JButton bt_adicionarMusica) {
        this.bt_adicionarMusica = bt_adicionarMusica;
    }

    public JButton getBt_criarPlaylist() {
        return bt_criarPlaylist;
    }

    public void setBt_criarPlaylist(JButton bt_criarPlaylist) {
        this.bt_criarPlaylist = bt_criarPlaylist;
    }

    public JButton getBt_voltarLog() {
        return bt_voltarLog;
    }

    public void setBt_voltarLog(JButton bt_voltarLog) {
        this.bt_voltarLog = bt_voltarLog;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLbl_tituloPlaylist() {
        return lbl_tituloPlaylist;
    }

    public void setLbl_tituloPlaylist(JLabel lbl_tituloPlaylist) {
        this.lbl_tituloPlaylist = lbl_tituloPlaylist;
    }

    public JTextArea getTxt_areaPlaylists() {
        return txt_areaPlaylists;
    }

    public void setTxt_areaPlaylists(JTextArea txt_areaPlaylists) {
        this.txt_areaPlaylists = txt_areaPlaylists;
    }

    public JTextField getTxt_nomeNovaPlaylist() {
        return txt_nomeNovaPlaylist;
    }

    public void setTxt_nomeNovaPlaylist(JTextField txt_nomeNovaPlaylist) {
        this.txt_nomeNovaPlaylist = txt_nomeNovaPlaylist;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloPlaylist = new javax.swing.JLabel();
        txt_nomeNovaPlaylist = new javax.swing.JTextField();
        bt_criarPlaylist = new javax.swing.JButton();
        bt_adicionarMusica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_areaPlaylists = new javax.swing.JTextArea();
        bt_voltarLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tituloPlaylist.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lbl_tituloPlaylist.setText("Minhas Playlists");

        txt_nomeNovaPlaylist.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nomeNovaPlaylist.setText("Nome da playlist");
        txt_nomeNovaPlaylist.setToolTipText("");
        txt_nomeNovaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeNovaPlaylistActionPerformed(evt);
            }
        });

        bt_criarPlaylist.setText("Criar Playlist");
        bt_criarPlaylist.setToolTipText("");
        bt_criarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_criarPlaylistActionPerformed(evt);
            }
        });

        bt_adicionarMusica.setText("Adicionar música atual");
        bt_adicionarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionarMusicaActionPerformed(evt);
            }
        });

        txt_areaPlaylists.setColumns(20);
        txt_areaPlaylists.setRows(5);
        jScrollPane1.setViewportView(txt_areaPlaylists);

        bt_voltarLog.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_voltarLog.setText("Voltar");
        bt_voltarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tituloPlaylist)
                .addGap(232, 232, 232))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_voltarLog)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bt_criarPlaylist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nomeNovaPlaylist, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_adicionarMusica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloPlaylist)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nomeNovaPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bt_adicionarMusica)
                .addGap(32, 32, 32)
                .addComponent(bt_criarPlaylist)
                .addGap(109, 109, 109)
                .addComponent(bt_voltarLog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeNovaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeNovaPlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeNovaPlaylistActionPerformed

    private void bt_voltarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarLogActionPerformed

    }//GEN-LAST:event_bt_voltarLogActionPerformed

    private void bt_adicionarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_adicionarMusicaActionPerformed

    private void bt_criarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criarPlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_criarPlaylistActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telaPlayslistUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telaPlayslistUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telaPlayslistUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telaPlayslistUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new telaPlayslistUser().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionarMusica;
    private javax.swing.JButton bt_criarPlaylist;
    private javax.swing.JButton bt_voltarLog;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_tituloPlaylist;
    private javax.swing.JTextArea txt_areaPlaylists;
    private javax.swing.JTextField txt_nomeNovaPlaylist;
    // End of variables declaration//GEN-END:variables
}
