/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author unifgalvarenga
 */
public class telaHistoricoUser extends javax.swing.JFrame {

    /**
     * Creates new form telaHistoricoUser
     */
    public telaHistoricoUser() {
        initComponents();
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }
    
    

    public JButton getBt_musicasCurtidas() {
        return bt_musicasCurtidas;
    }

    public void setBt_musicasCurtidas(JButton bt_musicasCurtidas) {
        this.bt_musicasCurtidas = bt_musicasCurtidas;
    }

    public JButton getBt_musicasDescurtidas() {
        return bt_musicasDescurtidas;
    }

    public void setBt_musicasDescurtidas(JButton bt_musicasDescurtidas) {
        this.bt_musicasDescurtidas = bt_musicasDescurtidas;
    }

    public JButton getBt_ultimasBuscas() {
        return bt_ultimasBuscas;
    }

    public void setBt_ultimasBuscas(JButton bt_ultimasBuscas) {
        this.bt_ultimasBuscas = bt_ultimasBuscas;
    }

    public JLabel getLbl_tituloLogin() {
        return lbl_tituloLogin;
    }

    public void setLbl_tituloLogin(JLabel lbl_tituloLogin) {
        this.lbl_tituloLogin = lbl_tituloLogin;
    }

    public JTextArea getTxt_areaHistoricoBuscas() {
        return txt_areaHistoricoBuscas;
    }

    public void setTxt_areaHistoricoBuscas(JTextArea txt_areaHistoricoBuscas) {
        this.txt_areaHistoricoBuscas = txt_areaHistoricoBuscas;
    }

    public JTextArea getTxt_areaHistoricoCurtidas() {
        return txt_areaHistoricoCurtidas;
    }

    public void setTxt_areaHistoricoCurtidas(JTextArea txt_areaHistoricoCurtidas) {
        this.txt_areaHistoricoCurtidas = txt_areaHistoricoCurtidas;
    }

    public JTextArea getTxt_areaHistoricoDescurtidas() {
        return txt_areaHistoricoDescurtidas;
    }

    public void setTxt_areaHistoricoDescurtidas(JTextArea txt_areaHistoricoDescurtidas) {
        this.txt_areaHistoricoDescurtidas = txt_areaHistoricoDescurtidas;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloLogin = new javax.swing.JLabel();
        bt_ultimasBuscas = new javax.swing.JButton();
        bt_musicasCurtidas = new javax.swing.JButton();
        bt_musicasDescurtidas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_areaHistoricoDescurtidas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_areaHistoricoBuscas = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_areaHistoricoCurtidas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tituloLogin.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lbl_tituloLogin.setText("Histórico");

        bt_ultimasBuscas.setText("ÚLTIMAS BUSCAS");
        bt_ultimasBuscas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ultimasBuscasActionPerformed(evt);
            }
        });

        bt_musicasCurtidas.setText("ÚLTIMAS CURTIDAS");
        bt_musicasCurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_musicasCurtidasActionPerformed(evt);
            }
        });

        bt_musicasDescurtidas.setText("ÚLTIMAS DESCURTIDAS");
        bt_musicasDescurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_musicasDescurtidasActionPerformed(evt);
            }
        });

        txt_areaHistoricoDescurtidas.setColumns(20);
        txt_areaHistoricoDescurtidas.setRows(5);
        jScrollPane1.setViewportView(txt_areaHistoricoDescurtidas);

        txt_areaHistoricoBuscas.setColumns(20);
        txt_areaHistoricoBuscas.setRows(5);
        jScrollPane2.setViewportView(txt_areaHistoricoBuscas);

        txt_areaHistoricoCurtidas.setColumns(20);
        txt_areaHistoricoCurtidas.setRows(5);
        jScrollPane3.setViewportView(txt_areaHistoricoCurtidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_musicasDescurtidas)
                            .addComponent(bt_musicasCurtidas)
                            .addComponent(bt_ultimasBuscas))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lbl_tituloLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_ultimasBuscas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_musicasCurtidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_musicasDescurtidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_musicasDescurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_musicasDescurtidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_musicasDescurtidasActionPerformed

    private void bt_musicasCurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_musicasCurtidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_musicasCurtidasActionPerformed

    private void bt_ultimasBuscasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ultimasBuscasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ultimasBuscasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telaHistoricoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telaHistoricoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telaHistoricoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telaHistoricoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new telaHistoricoUser().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_musicasCurtidas;
    private javax.swing.JButton bt_musicasDescurtidas;
    private javax.swing.JButton bt_ultimasBuscas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_tituloLogin;
    private javax.swing.JTextArea txt_areaHistoricoBuscas;
    private javax.swing.JTextArea txt_areaHistoricoCurtidas;
    private javax.swing.JTextArea txt_areaHistoricoDescurtidas;
    // End of variables declaration//GEN-END:variables
}
