/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControleCadUser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifgalvarenga
 */
public class telaCadUser extends javax.swing.JFrame {

    /**
     * Creates new form telaCadUser
     */
    public telaCadUser() {
        initComponents();
        ccu = new ControleCadUser(this);
    }

    public JButton getBt_cadUser() {
        return bt_cadUser;
    }

    public void setBt_cadUser(JButton bt_cadUser) {
        this.bt_cadUser = bt_cadUser;
    }

    public JButton getBt_voltarCadUser() {
        return bt_voltarCadUser;
    }

    public void setBt_voltarCadUser(JButton bt_voltarCadUser) {
        this.bt_voltarCadUser = bt_voltarCadUser;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getLbl_cadUserEmail() {
        return lbl_cadUserEmail;
    }

    public void setLbl_cadUserEmail(JLabel lbl_cadUserEmail) {
        this.lbl_cadUserEmail = lbl_cadUserEmail;
    }

    public JLabel getLbl_cadUserNome() {
        return lbl_cadUserNome;
    }

    public void setLbl_cadUserNome(JLabel lbl_cadUserNome) {
        this.lbl_cadUserNome = lbl_cadUserNome;
    }

    public JLabel getLbl_cadUserResult() {
        return lbl_cadUserResult;
    }

    public void setLbl_cadUserResult(JLabel lbl_cadUserResult) {
        this.lbl_cadUserResult = lbl_cadUserResult;
    }

    public JLabel getLbl_cadUserSenha() {
        return lbl_cadUserSenha;
    }

    public void setLbl_cadUserSenha(JLabel lbl_cadUserSenha) {
        this.lbl_cadUserSenha = lbl_cadUserSenha;
    }

    public JTextField getTxt_cadUserEmail() {
        return txt_cadUserEmail;
    }

    public void setTxt_cadUserEmail(JTextField txt_cadUserEmail) {
        this.txt_cadUserEmail = txt_cadUserEmail;
    }

    public JTextField getTxt_cadUserNome() {
        return txt_cadUserNome;
    }

    public void setTxt_cadUserNome(JTextField txt_cadUserNome) {
        this.txt_cadUserNome = txt_cadUserNome;
    }

    public JTextField getTxt_cadUserSenha() {
        return txt_cadUserSenha;
    }

    public void setTxt_cadUserSenha(JTextField txt_cadUserSenha) {
        this.txt_cadUserSenha = txt_cadUserSenha;
    }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel lbl_tituloCadUser = new javax.swing.JLabel();
        lbl_cadUserNome = new javax.swing.JLabel();
        txt_cadUserNome = new javax.swing.JTextField();
        lbl_cadUserEmail = new javax.swing.JLabel();
        txt_cadUserEmail = new javax.swing.JTextField();
        lbl_cadUserSenha = new javax.swing.JLabel();
        txt_cadUserSenha = new javax.swing.JTextField();
        bt_cadUser = new javax.swing.JButton();
        bt_voltarCadUser = new javax.swing.JButton();
        lbl_cadUserResult = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 82, 201));

        lbl_tituloCadUser.setBackground(new java.awt.Color(255, 255, 255));
        lbl_tituloCadUser.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lbl_tituloCadUser.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tituloCadUser.setText("CADASTRAR USUÁRIOS");

        lbl_cadUserNome.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_cadUserNome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cadUserNome.setText("Nome:");

        txt_cadUserNome.setBackground(new java.awt.Color(204, 204, 204));
        txt_cadUserNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cadUserNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadUserNomeActionPerformed(evt);
            }
        });

        lbl_cadUserEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_cadUserEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cadUserEmail.setText("Email:");

        txt_cadUserEmail.setBackground(new java.awt.Color(204, 204, 204));
        txt_cadUserEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cadUserEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadUserEmailActionPerformed(evt);
            }
        });

        lbl_cadUserSenha.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_cadUserSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cadUserSenha.setText("Senha:");

        txt_cadUserSenha.setBackground(new java.awt.Color(204, 204, 204));
        txt_cadUserSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cadUserSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadUserSenhaActionPerformed(evt);
            }
        });

        bt_cadUser.setBackground(new java.awt.Color(0, 0, 0));
        bt_cadUser.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_cadUser.setForeground(new java.awt.Color(255, 255, 255));
        bt_cadUser.setText("CADASTRAR");
        bt_cadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadUserActionPerformed(evt);
            }
        });

        bt_voltarCadUser.setBackground(new java.awt.Color(0, 0, 0));
        bt_voltarCadUser.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_voltarCadUser.setForeground(new java.awt.Color(255, 255, 255));
        bt_voltarCadUser.setText("Voltar");
        bt_voltarCadUser.setActionCommand("");
        bt_voltarCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarCadUserActionPerformed(evt);
            }
        });

        lbl_cadUserResult.setFont(new java.awt.Font("Swis721 Cn BT", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_cadUserNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_cadUserEmail))
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_cadUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_cadUserNome, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lbl_tituloCadUser)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_cadUserSenha)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_cadUserSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_cadUser)
                                .addGap(68, 68, 68))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_voltarCadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_cadUserResult, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloCadUser)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadUserNome)
                    .addComponent(txt_cadUserNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadUserEmail)
                    .addComponent(txt_cadUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadUserSenha)
                    .addComponent(txt_cadUserSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(bt_cadUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_voltarCadUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cadUserResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cadUserNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadUserNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadUserNomeActionPerformed

    private void txt_cadUserEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadUserEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadUserEmailActionPerformed

    private void bt_cadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadUserActionPerformed
       ccu.cadastrarUsuario();
    }//GEN-LAST:event_bt_cadUserActionPerformed

    private void bt_voltarCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarCadUserActionPerformed
        ccu.voltaMenu();
    }//GEN-LAST:event_bt_voltarCadUserActionPerformed

    private void txt_cadUserSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadUserSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadUserSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new telaCadUser().setVisible(true);
//            }
//        });
//    }
    
    private final ControleCadUser ccu;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadUser;
    private javax.swing.JButton bt_voltarCadUser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cadUserEmail;
    private javax.swing.JLabel lbl_cadUserNome;
    private javax.swing.JLabel lbl_cadUserResult;
    private javax.swing.JLabel lbl_cadUserSenha;
    private javax.swing.JTextField txt_cadUserEmail;
    private javax.swing.JTextField txt_cadUserNome;
    private javax.swing.JTextField txt_cadUserSenha;
    // End of variables declaration//GEN-END:variables
}
