/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import Controller.ControleHistoricoUser;

/**
 *
 * @author unifgalvarenga
 */
public class telaHistoricoUser extends javax.swing.JFrame {

    /**
     * Creates new form telaHistoricoUser
     */
    public telaHistoricoUser() {
        initComponents();
        chu = new ControleHistoricoUser(this);
    }

    public JLabel getLbl_tituloLogin() {
        return lbl_tituloLogin;
    }

    public void setLbl_tituloLogin(JLabel lbl_tituloLogin) {
        this.lbl_tituloLogin = lbl_tituloLogin;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JScrollPane getjScrollPane5() {
        return jScrollPane5;
    }

    public void setjScrollPane5(JScrollPane jScrollPane5) {
        this.jScrollPane5 = jScrollPane5;
    }

    public JScrollPane getjScrollPane6() {
        return jScrollPane6;
    }

    public void setjScrollPane6(JScrollPane jScrollPane6) {
        this.jScrollPane6 = jScrollPane6;
    }

    public JList<String> getJl_buscaCurtHist() {
        return jl_buscaCurtHist;
    }

    public void setJl_buscaCurtHist(JList<String> jl_buscaCurtHist) {
        this.jl_buscaCurtHist = jl_buscaCurtHist;
    }

    public JList<String> getJl_buscaDescHist() {
        return jl_buscaDescHist;
    }

    public void setJl_buscaDescHist(JList<String> jl_buscaDescHist) {
        this.jl_buscaDescHist = jl_buscaDescHist;
    }

    public JList<String> getJl_buscaMusHist() {
        return jl_buscaMusHist;
    }

    public void setJl_buscaMusHist(JList<String> jl_buscaMusHist) {
        this.jl_buscaMusHist = jl_buscaMusHist;
    }

    public JLabel getLbl_busCurtHist() {
        return lbl_busCurtHist;
    }

    public void setLbl_busCurtHist(JLabel lbl_busCurtHist) {
        this.lbl_busCurtHist = lbl_busCurtHist;
    }

    public JLabel getLbl_busDescHist() {
        return lbl_busDescHist;
    }

    public void setLbl_busDescHist(JLabel lbl_busDescHist) {
        this.lbl_busDescHist = lbl_busDescHist;
    }

    public JLabel getLbl_busMusHist() {
        return lbl_busMusHist;
    }

    public void setLbl_busMusHist(JLabel lbl_busMusHist) {
        this.lbl_busMusHist = lbl_busMusHist;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloLogin = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_buscaMusHist = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_buscaCurtHist = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_buscaDescHist = new javax.swing.JList<>();
        lbl_busMusHist = new javax.swing.JLabel();
        lbl_busCurtHist = new javax.swing.JLabel();
        lbl_busDescHist = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bt_voltarLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tituloLogin.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lbl_tituloLogin.setText("Histórico");

        jl_buscaMusHist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jl_buscaMusHist);

        jl_buscaCurtHist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jl_buscaCurtHist);

        jl_buscaDescHist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jl_buscaDescHist);

        lbl_busMusHist.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_busMusHist.setText("Histórico Buscas");
        lbl_busMusHist.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbl_busCurtHist.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_busCurtHist.setText("Históricos Curtidas");

        lbl_busDescHist.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_busDescHist.setText("Histórico Descurtidas");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img_refresh.png"))); // NOI18N

        bt_voltarLog.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_voltarLog.setText("Voltar");
        bt_voltarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_busMusHist, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_busCurtHist, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_busDescHist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_voltarLog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_busMusHist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_busCurtHist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_busDescHist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_voltarLog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarLogActionPerformed
        chu.voltarLog();
    }//GEN-LAST:event_bt_voltarLogActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telaHistoricoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telaHistoricoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telaHistoricoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telaHistoricoUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new telaHistoricoUser().setVisible(true);
//            }
//        });
//    }
    
    private final ControleHistoricoUser chu;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_voltarLog;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> jl_buscaCurtHist;
    private javax.swing.JList<String> jl_buscaDescHist;
    private javax.swing.JList<String> jl_buscaMusHist;
    private javax.swing.JLabel lbl_busCurtHist;
    private javax.swing.JLabel lbl_busDescHist;
    private javax.swing.JLabel lbl_busMusHist;
    private javax.swing.JLabel lbl_tituloLogin;
    // End of variables declaration//GEN-END:variables
}
