/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JLabel;
import javax.swing.JPanel;
import Controller.ControleEstatisticas;
import javax.swing.JList;

/**
 *
 * @author Win 10
 */
public class telaEstatisticas extends javax.swing.JFrame {

    /**
     * Creates new form telaEstatisticas
     */
    public telaEstatisticas() {
        initComponents();
        ce = new ControleEstatisticas(this);
    }

    public JPanel getJp_totais() {
        return jp_totais;
    }

    public void setJp_totais(JPanel jp_totais) {
        this.jp_totais = jp_totais;
    }

    public JLabel getLbl_tituloLogin() {
        return lbl_tituloLogin;
    }

    public void setLbl_tituloLogin(JLabel lbl_tituloLogin) {
        this.lbl_tituloLogin = lbl_tituloLogin;
    }

    public JLabel getLbl_totMusEst() {
        return lbl_totMusEst;
    }

    public void setLbl_totMusEst(JLabel lbl_totMusEst) {
        this.lbl_totMusEst = lbl_totMusEst;
    }

    public JLabel getLbl_totMusEstRes() {
        return lbl_totMusEstRes;
    }

    public void setLbl_totMusEstRes(JLabel lbl_totMusEstRes) {
        this.lbl_totMusEstRes = lbl_totMusEstRes;
    }

    public JLabel getLbl_totUserEst() {
        return lbl_totUserEst;
    }

    public void setLbl_totUserEst(JLabel lbl_totUserEst) {
        this.lbl_totUserEst = lbl_totUserEst;
    }

    public JLabel getLbl_totUserEstRes() {
        return lbl_totUserEstRes;
    }

    public void setLbl_totUserEstRes(JLabel lbl_totUserEstRes) {
        this.lbl_totUserEstRes = lbl_totUserEstRes;
    }

    public JList<String> getJlist_top5MusDes() {
        return jlist_top5MusDes;
    }

    public void setJlist_top5MusDes(JList<String> jlist_top5MusDes) {
        this.jlist_top5MusDes = jlist_top5MusDes;
    }
    
    public JList<String> getJlist_top5Mus() {
        return jlist_top5Mus;
    }

    public void setJlist_top5Mus(JList<String> jlist_top5Mus) {
        this.jlist_top5Mus = jlist_top5Mus;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloLogin = new javax.swing.JLabel();
        lbl_top5MusLik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_top5Mus = new javax.swing.JList<>();
        lbl_top5MusDes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist_top5MusDes = new javax.swing.JList<>();
        jp_totais = new javax.swing.JPanel();
        lbl_totUserEst = new javax.swing.JLabel();
        lbl_totMusEst = new javax.swing.JLabel();
        lbl_totUserEstRes = new javax.swing.JLabel();
        lbl_totMusEstRes = new javax.swing.JLabel();
        bt_voltarEst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 82, 201));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));

        lbl_tituloLogin.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lbl_tituloLogin.setText("ESTATÍSTICAS");

        lbl_top5MusLik.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_top5MusLik.setText("Musicas Mais Curtidas no Spotifei");

        jlist_top5Mus.setBackground(new java.awt.Color(0, 0, 0));
        jlist_top5Mus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        jlist_top5Mus.setForeground(new java.awt.Color(255, 255, 255));
        jlist_top5Mus.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlist_top5Mus);

        lbl_top5MusDes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_top5MusDes.setText("Musicas Menos Curtidas no Spotifei");

        jlist_top5MusDes.setBackground(new java.awt.Color(0, 0, 0));
        jlist_top5MusDes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        jlist_top5MusDes.setForeground(new java.awt.Color(255, 255, 255));
        jlist_top5MusDes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlist_top5MusDes);

        jp_totais.setBackground(new java.awt.Color(0, 0, 0));
        jp_totais.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));

        lbl_totUserEst.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_totUserEst.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totUserEst.setText("Total de Usuários Hoje: ");

        lbl_totMusEst.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_totMusEst.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totMusEst.setText("Total de Músicas Hoje: ");

        lbl_totUserEstRes.setBackground(new java.awt.Color(0, 0, 0));
        lbl_totUserEstRes.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        lbl_totUserEstRes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totUserEstRes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));

        lbl_totMusEstRes.setBackground(new java.awt.Color(0, 0, 0));
        lbl_totMusEstRes.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        lbl_totMusEstRes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totMusEstRes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));

        javax.swing.GroupLayout jp_totaisLayout = new javax.swing.GroupLayout(jp_totais);
        jp_totais.setLayout(jp_totaisLayout);
        jp_totaisLayout.setHorizontalGroup(
            jp_totaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_totaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_totaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_totUserEst)
                    .addComponent(lbl_totMusEst))
                .addGap(18, 18, 18)
                .addGroup(jp_totaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_totMusEstRes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_totUserEstRes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jp_totaisLayout.setVerticalGroup(
            jp_totaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_totaisLayout.createSequentialGroup()
                .addGroup(jp_totaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_totaisLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_totUserEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_totaisLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_totUserEstRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jp_totaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_totaisLayout.createSequentialGroup()
                        .addComponent(lbl_totMusEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jp_totaisLayout.createSequentialGroup()
                        .addComponent(lbl_totMusEstRes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        bt_voltarEst.setBackground(new java.awt.Color(255, 0, 0));
        bt_voltarEst.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_voltarEst.setText("Voltar");
        bt_voltarEst.setActionCommand("");
        bt_voltarEst.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        bt_voltarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarEstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tituloLogin)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_top5MusLik)
                        .addGap(76, 76, 76))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(lbl_top5MusDes)
                .addGap(56, 73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_totais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_voltarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_top5MusLik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_totais, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_top5MusDes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_voltarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void bt_voltarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarEstActionPerformed
        ce.voltaMenu();
    }//GEN-LAST:event_bt_voltarEstActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telaEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new telaEstatisticas().setVisible(true);
//            }
//        });
//    }

    
    private final ControleEstatisticas ce;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_voltarEst;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlist_top5Mus;
    private javax.swing.JList<String> jlist_top5MusDes;
    private javax.swing.JPanel jp_totais;
    private javax.swing.JLabel lbl_tituloLogin;
    private javax.swing.JLabel lbl_top5MusDes;
    private javax.swing.JLabel lbl_top5MusLik;
    private javax.swing.JLabel lbl_totMusEst;
    private javax.swing.JLabel lbl_totMusEstRes;
    private javax.swing.JLabel lbl_totUserEst;
    private javax.swing.JLabel lbl_totUserEstRes;
    // End of variables declaration//GEN-END:variables
}
