/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import Controller.ControleMenuUser;

/**
 *
 * @author Win 10
 */
public class telaMenuUser extends javax.swing.JFrame {


    public telaMenuUser() {
        initComponents();
        cmu = new ControleMenuUser(this);
        pn_infoMus.setVisible(false);

    }

    public JLabel getLbl_sourcNomeMusRes() {
        return lbl_sourcNomeMusRes;
    }

    public void setLbl_sourcNomeMusRes(JLabel lbl_sourcNomeMusRes) {
        this.lbl_sourcNomeMusRes = lbl_sourcNomeMusRes;
    }
    
    

    public JButton getBt_souceMus() {
        return bt_souceMus;
    }

    public void setBt_souceMus(JButton bt_souceMus) {
        this.bt_souceMus = bt_souceMus;
    }

    public JLabel getLbl_cadMusName() {
        return lbl_sourcNomeMusRes;
    }

    public void setLbl_cadMusName(JLabel lbl_cadMusName) {
        this.lbl_sourcNomeMusRes = lbl_cadMusName;
    }

    public JLabel getLbl_sourMusArt() {
        return lbl_sourMusArt;
    }

    public void setLbl_sourMusArt(JLabel lbl_sourMusArt) {
        this.lbl_sourMusArt = lbl_sourMusArt;
    }

    public JLabel getLbl_sourMusGener() {
        return lbl_sourMusGener;
    }

    public void setLbl_sourMusGener(JLabel lbl_sourMusGener) {
        this.lbl_sourMusGener = lbl_sourMusGener;
    }

    public JLabel getLbl_sourMusYear() {
        return lbl_sourMusYear;
    }

    public void setLbl_sourMusYear(JLabel lbl_sourMusYear) {
        this.lbl_sourMusYear = lbl_sourMusYear;
    }

    public JPanel getPn_infoMus() {
        return pn_infoMus;
    }

    public JLabel getLbl_sourMusStatus() {
        return lbl_sourMusStatus;
    }

    public void setLbl_sourMusStatus(JLabel lbl_sourMusStatus) {
        this.lbl_sourMusStatus = lbl_sourMusStatus;
    }

    public void setPn_infoMus(JPanel pn_infoMus) {
        this.pn_infoMus = pn_infoMus;
    }

    public JTextField getTxt_barraPesquisaMus() {
        return txt_barraPesquisaMus;
    }

    public void setTxt_barraPesquisaMus(JTextField txt_barraPesquisaMus) {
        this.txt_barraPesquisaMus = txt_barraPesquisaMus;
    }

    public JTextField getTxt_sourMusAno() {
        return txt_sourMusAno;
    }

    public void setTxt_sourMusAno(JTextField txt_sourMusAno) {
        this.txt_sourMusAno = txt_sourMusAno;
    }

    public JTextField getTxt_sourMusArt() {
        return txt_sourMusArt;
    }

    public void setTxt_sourMusArt(JTextField txt_sourMusArt) {
        this.txt_sourMusArt = txt_sourMusArt;
    }

    public JTextField getTxt_sourMusGener() {
        return txt_sourMusGener;
    }

    public void setTxt_sourMusGener(JTextField txt_sourMusGener) {
        this.txt_sourMusGener = txt_sourMusGener;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_barraPesquisaMus = new javax.swing.JTextField();
        bt_souceMus = new javax.swing.JButton();
        pn_infoMus = new javax.swing.JPanel();
        lbl_sourMusArt = new javax.swing.JLabel();
        txt_sourMusArt = new javax.swing.JTextField();
        lbl_sourcNomeMusRes = new javax.swing.JLabel();
        lbl_sourMusYear = new javax.swing.JLabel();
        txt_sourMusAno = new javax.swing.JTextField();
        lbl_sourMusGener = new javax.swing.JLabel();
        txt_sourMusGener = new javax.swing.JTextField();
        lbl_sourMusStatus = new javax.swing.JLabel();
        bt_fechaSource = new javax.swing.JButton();
        bt_voltarLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_barraPesquisaMus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_barraPesquisaMus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_barraPesquisaMusActionPerformed(evt);
            }
        });

        bt_souceMus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img_source.png"))); // NOI18N
        bt_souceMus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_souceMusActionPerformed(evt);
            }
        });

        lbl_sourMusArt.setFont(new java.awt.Font("Swis721 Cn BT", 1, 14)); // NOI18N
        lbl_sourMusArt.setText("Artista");

        txt_sourMusArt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sourMusArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sourMusArtActionPerformed(evt);
            }
        });

        lbl_sourcNomeMusRes.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N

        lbl_sourMusYear.setFont(new java.awt.Font("Swis721 Cn BT", 1, 14)); // NOI18N
        lbl_sourMusYear.setText("Ano");

        txt_sourMusAno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sourMusAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sourMusAnoActionPerformed(evt);
            }
        });

        lbl_sourMusGener.setFont(new java.awt.Font("Swis721 Cn BT", 1, 14)); // NOI18N
        lbl_sourMusGener.setText("Genero");

        txt_sourMusGener.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sourMusGener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sourMusGenerActionPerformed(evt);
            }
        });

        lbl_sourMusStatus.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N

        bt_fechaSource.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_fechaSource.setText("X");
        bt_fechaSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fechaSourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_infoMusLayout = new javax.swing.GroupLayout(pn_infoMus);
        pn_infoMus.setLayout(pn_infoMusLayout);
        pn_infoMusLayout.setHorizontalGroup(
            pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_infoMusLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_sourMusArt)
                    .addComponent(lbl_sourMusYear)
                    .addComponent(lbl_sourMusGener))
                .addGap(18, 18, 18)
                .addGroup(pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_sourMusGener)
                    .addComponent(txt_sourMusAno)
                    .addComponent(txt_sourMusArt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_infoMusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_infoMusLayout.createSequentialGroup()
                        .addComponent(lbl_sourcNomeMusRes, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(bt_fechaSource, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_infoMusLayout.createSequentialGroup()
                        .addComponent(lbl_sourMusStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );
        pn_infoMusLayout.setVerticalGroup(
            pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_infoMusLayout.createSequentialGroup()
                .addGroup(pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_infoMusLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_sourcNomeMusRes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_infoMusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_fechaSource, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sourMusArt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sourMusArt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sourMusAno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sourMusYear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pn_infoMusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sourMusGener, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sourMusGener, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_sourMusStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        bt_voltarLog.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_voltarLog.setText("Voltar");
        bt_voltarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pn_infoMus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_barraPesquisaMus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_souceMus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bt_voltarLog)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_souceMus, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txt_barraPesquisaMus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_infoMus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(bt_voltarLog, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_barraPesquisaMusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_barraPesquisaMusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barraPesquisaMusActionPerformed

    private void bt_souceMusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_souceMusActionPerformed
        cmu.pesquisarMusica();
    }//GEN-LAST:event_bt_souceMusActionPerformed

    private void txt_sourMusArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sourMusArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sourMusArtActionPerformed

    private void txt_sourMusAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sourMusAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sourMusAnoActionPerformed

    private void txt_sourMusGenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sourMusGenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sourMusGenerActionPerformed

    private void bt_fechaSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fechaSourceActionPerformed
        cmu.sairSource();
    }//GEN-LAST:event_bt_fechaSourceActionPerformed

    private void bt_voltarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarLogActionPerformed
        cmu.voltarLog();
    }//GEN-LAST:event_bt_voltarLogActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telaMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telaMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telaMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telaMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new telaMenuUser().setVisible(true);
//            }
//        });
//    }
    private final ControleMenuUser cmu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_fechaSource;
    private javax.swing.JButton bt_souceMus;
    private javax.swing.JButton bt_voltarLog;
    private javax.swing.JLabel lbl_sourMusArt;
    private javax.swing.JLabel lbl_sourMusGener;
    private javax.swing.JLabel lbl_sourMusStatus;
    private javax.swing.JLabel lbl_sourMusYear;
    private javax.swing.JLabel lbl_sourcNomeMusRes;
    private javax.swing.JPanel pn_infoMus;
    private javax.swing.JTextField txt_barraPesquisaMus;
    private javax.swing.JTextField txt_sourMusAno;
    private javax.swing.JTextField txt_sourMusArt;
    private javax.swing.JTextField txt_sourMusGener;
    // End of variables declaration//GEN-END:variables
}
