/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.ControleLogin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifbcosta
 */
public class telaLogCad extends javax.swing.JFrame {
    
    public telaLogCad() {
        initComponents();
        cl = new ControleLogin(this);
    }

    public JButton getBt_cadastrar() {
        return bt_cadastrar;
    }

    public void setBt_cadastrar(JButton bt_cadastrar) {
        this.bt_cadastrar = bt_cadastrar;
    }

    public JButton getBt_loginADM() {
        return bt_loginADM;
    }

    public void setBt_loginADM(JButton bt_loginADM) {
        this.bt_loginADM = bt_loginADM;
    }

    public JButton getBt_loginUsuario() {
        return bt_loginUsuario;
    }

    public void setBt_loginUsuario(JButton bt_loginUsuario) {
        this.bt_loginUsuario = bt_loginUsuario;
    }

    public JLabel getLbl_nomeLogin() {
        return lbl_nomeLogin;
    }

    public void setLbl_nomeLogin(JLabel lbl_nomeLogin) {
        this.lbl_nomeLogin = lbl_nomeLogin;
    }

    public JLabel getLbl_senhaLogin() {
        return lbl_senhaLogin;
    }

    public void setLbl_senhaLogin(JLabel lbl_senhaLogin) {
        this.lbl_senhaLogin = lbl_senhaLogin;
    }

    public JLabel getLbl_tituloLogin() {
        return lbl_tituloLogin;
    }

    public void setLbl_tituloLogin(JLabel lbl_tituloLogin) {
        this.lbl_tituloLogin = lbl_tituloLogin;
    }

    public JTextField getTxt_nomeLogin() {
        return txt_nomeLogin;
    }

    public void setTxt_nomeLogin(JTextField txt_nomeLogin) {
        this.txt_nomeLogin = txt_nomeLogin;
    }

    public JTextField getTxt_senhaLogin() {
        return txt_senhaLogin;
    }

    public void setTxt_senhaLogin(JTextField txt_senhaLogin) {
        this.txt_senhaLogin = txt_senhaLogin;
    }

    public JTextField getTxt_textoAviso() {
        return txt_textoAviso;
    }

    public void setTxt_textoAviso(JTextField txt_textoAviso) {
        this.txt_textoAviso = txt_textoAviso;
    }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        panel1 = new java.awt.Panel();
        lbl_tituloLogin = new javax.swing.JLabel();
        lbl_nomeLogin = new javax.swing.JLabel();
        lbl_senhaLogin = new javax.swing.JLabel();
        txt_nomeLogin = new javax.swing.JTextField();
        txt_senhaLogin = new javax.swing.JTextField();
        bt_loginADM = new javax.swing.JButton();
        bt_loginUsuario = new javax.swing.JButton();
        bt_cadastrar = new javax.swing.JButton();
        txt_textoAviso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        panel1.setBackground(new java.awt.Color(42, 82, 201));

        lbl_tituloLogin.setBackground(new java.awt.Color(42, 82, 201));
        lbl_tituloLogin.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lbl_tituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloLogin.setText("Login");
        lbl_tituloLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));

        lbl_nomeLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_nomeLogin.setText("Usuário: ");

        lbl_senhaLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_senhaLogin.setText("Senha: ");

        txt_nomeLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nomeLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        txt_nomeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeLoginActionPerformed(evt);
            }
        });

        txt_senhaLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_senhaLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        txt_senhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaLoginActionPerformed(evt);
            }
        });

        bt_loginADM.setBackground(new java.awt.Color(102, 255, 102));
        bt_loginADM.setFont(new java.awt.Font("Leelawadee", 3, 14)); // NOI18N
        bt_loginADM.setText("Login ADM");
        bt_loginADM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        bt_loginADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginADMActionPerformed(evt);
            }
        });

        bt_loginUsuario.setBackground(new java.awt.Color(102, 255, 102));
        bt_loginUsuario.setFont(new java.awt.Font("Leelawadee", 3, 14)); // NOI18N
        bt_loginUsuario.setText("Login Usuário");
        bt_loginUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        bt_loginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginUsuarioActionPerformed(evt);
            }
        });

        bt_cadastrar.setBackground(new java.awt.Color(102, 255, 102));
        bt_cadastrar.setFont(new java.awt.Font("Leelawadee", 3, 14)); // NOI18N
        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });

        txt_textoAviso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_textoAviso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        txt_textoAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_textoAvisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(bt_loginADM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_loginUsuario)
                        .addGap(54, 54, 54)
                        .addComponent(bt_cadastrar))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_nomeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_senhaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nomeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_senhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_textoAviso)
                    .addComponent(lbl_tituloLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeLogin)
                    .addComponent(txt_nomeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senhaLogin)
                    .addComponent(txt_senhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadastrar)
                    .addComponent(bt_loginUsuario)
                    .addComponent(bt_loginADM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_textoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginUsuarioActionPerformed
        cl.fazerLoginUser();
    }//GEN-LAST:event_bt_loginUsuarioActionPerformed

    private void txt_nomeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeLoginActionPerformed

    private void bt_loginADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginADMActionPerformed
        cl.fazerLoginAdm();
    }//GEN-LAST:event_bt_loginADMActionPerformed

    private void txt_textoAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_textoAvisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_textoAvisoActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        cl.telaCadUser();
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void txt_senhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaLoginActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telalogin_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telalogin_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telalogin_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telalogin_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new telalogin_cadastro().setVisible(true);
//            }
//        });
//    }
 private final ControleLogin cl;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_loginADM;
    private javax.swing.JButton bt_loginUsuario;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel lbl_nomeLogin;
    private javax.swing.JLabel lbl_senhaLogin;
    private javax.swing.JLabel lbl_tituloLogin;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txt_nomeLogin;
    private javax.swing.JTextField txt_senhaLogin;
    private javax.swing.JTextField txt_textoAviso;
    // End of variables declaration//GEN-END:variables
}
