/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControleCadUser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifgalvarenga
 */
public class telaCadUser extends javax.swing.JFrame {

    /**
     * Creates new form telaCadUser
     */
    public telaCadUser() {
        initComponents();
        ccu = new ControleCadUser(this);
    }

    public JButton getBt_cadUser() {
        return bt_cadUser;
    }

    public void setBt_cadUser(JButton bt_cadUser) {
        this.bt_cadUser = bt_cadUser;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getLbl_cadEmail() {
        return lbl_cadEmail;
    }

    public void setLbl_cadEmail(JLabel lbl_cadEmail) {
        this.lbl_cadEmail = lbl_cadEmail;
    }

    public JLabel getLbl_cadIdade() {
        return lbl_cadIdade;
    }

    public void setLbl_cadIdade(JLabel lbl_cadIdade) {
        this.lbl_cadIdade = lbl_cadIdade;
    }

    public JLabel getLbl_cadNome() {
        return lbl_cadNome;
    }

    public void setLbl_cadNome(JLabel lbl_cadNome) {
        this.lbl_cadNome = lbl_cadNome;
    }

    public JLabel getLbl_tituloCadUser() {
        return lbl_tituloCadUser;
    }

    public void setLbl_tituloCadUser(JLabel lbl_tituloCadUser) {
        this.lbl_tituloCadUser = lbl_tituloCadUser;
    }

    public JTextField getTxt_cadEmail() {
        return txt_cadEmail;
    }

    public void setTxt_cadEmail(JTextField txt_cadEmail) {
        this.txt_cadEmail = txt_cadEmail;
    }

    public JTextField getTxt_cadIdade() {
        return txt_cadIdade;
    }

    public void setTxt_cadIdade(JTextField txt_cadIdade) {
        this.txt_cadIdade = txt_cadIdade;
    }

    public JTextField getTxt_cadNome() {
        return txt_cadNome;
    }

    public void setTxt_cadNome(JTextField txt_cadNome) {
        this.txt_cadNome = txt_cadNome;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lbl_tituloCadUser = new javax.swing.JLabel();
        txt_cadNome = new javax.swing.JTextField();
        txt_cadIdade = new javax.swing.JTextField();
        txt_cadEmail = new javax.swing.JTextField();
        lbl_cadNome = new javax.swing.JLabel();
        lbl_cadEmail = new javax.swing.JLabel();
        lbl_cadIdade = new javax.swing.JLabel();
        bt_cadUser = new javax.swing.JButton();
        bt_voltarGenArt = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tituloCadUser.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        lbl_tituloCadUser.setText("CADASTRAR USUÁRIOS");

        txt_cadNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cadNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadNomeActionPerformed(evt);
            }
        });

        txt_cadIdade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cadIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadIdadeActionPerformed(evt);
            }
        });

        txt_cadEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cadEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cadEmailActionPerformed(evt);
            }
        });

        lbl_cadNome.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_cadNome.setText("Nome:");

        lbl_cadEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_cadEmail.setText("Email:");

        lbl_cadIdade.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_cadIdade.setText("Idade:");

        bt_cadUser.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_cadUser.setText("CADASTRAR");
        bt_cadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadUserActionPerformed(evt);
            }
        });

        bt_voltarGenArt.setFont(new java.awt.Font("Leelawadee", 3, 12)); // NOI18N
        bt_voltarGenArt.setText("Voltar");
        bt_voltarGenArt.setActionCommand("");
        bt_voltarGenArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarGenArtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(bt_cadUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cadEmail)
                                    .addComponent(lbl_cadIdade))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_cadNome)
                                    .addComponent(txt_cadIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_tituloCadUser)))
                    .addComponent(bt_voltarGenArt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloCadUser)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cadNome))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadEmail)
                    .addComponent(txt_cadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cadIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cadIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(bt_cadUser)
                .addGap(20, 20, 20)
                .addComponent(bt_voltarGenArt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cadNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadNomeActionPerformed

    private void txt_cadIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadIdadeActionPerformed

    private void txt_cadEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cadEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cadEmailActionPerformed

    private void bt_cadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadUserActionPerformed
       ccu.cadastrarUsuario();
    }//GEN-LAST:event_bt_cadUserActionPerformed

    private void bt_voltarGenArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarGenArtActionPerformed
        ccu.voltaMenu();
    }//GEN-LAST:event_bt_voltarGenArtActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(telaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(telaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(telaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(telaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new telaCadUser().setVisible(true);
//            }
//        });
//    }
    
    private final ControleCadUser ccu;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadUser;
    private javax.swing.JButton bt_voltarGenArt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lbl_cadEmail;
    private javax.swing.JLabel lbl_cadIdade;
    private javax.swing.JLabel lbl_cadNome;
    private javax.swing.JLabel lbl_tituloCadUser;
    private javax.swing.JTextField txt_cadEmail;
    private javax.swing.JTextField txt_cadIdade;
    private javax.swing.JTextField txt_cadNome;
    // End of variables declaration//GEN-END:variables
}
